export const cartePossibili = [ {nome: 'snowman', icona:'⛄'},
                                {nome: 'person with ball', icona:'⛹'},
                                {nome: 'hot beverage', icona:'☕'},
                                {nome: 'umbrella with rain drops', icona:'☔'},
                                {nome: 'skull and crossbones', icona:'☠'},
                                {nome: 'radioactive', icona:'☢'},
                                {nome: 'black telephone', icona:'☎'},
                                {nome: 'black heart suit', icona:'♥'},
                                {nome: 'black club suit', icona:'♣'},
                                {nome: 'black spade suit', icona:'♠'},
                                {nome: 'black diamond suit', icona:'♦'},
                                {nome: 'Unicorn Face', icona:'🦄'},
                                {nome: 'Ram', icona:'🐏'},
                                {nome: 'Owl', icona:'🦉'},
                                {nome: 'Light Bulb', icona:'💡'},
                                {nome: 'Gem Stone', icona:'💎'},
                                {nome: 'Crossed Swords', icona:'⚔'},
                                {nome: 'Party Popper', icona:'🎉'},
                                {nome: 'Television', icona:'📺'},
                                {nome: 'Radio', icona:'📻'},
                                {nome: 'Wrench', icona:'🔧'},
                                {nome: 'Motorcycle', icona:'🏍'},
                                {nome: 'Rocket', icona:'🚀'},
                                {nome: 'High-Speed Train', icona:'🚄'},
                                {nome: 'Racing Car', icona:'🏎'},
                                {nome: 'Satellite', icona:'🛰'},
                                {nome: 'Automobile', icona:'🚗'},
                                {nome: 'Motor Scooter', icona:'🛵'},
                                {nome: 'Flying Saucer', icona:'🛸'},
                                {nome: 'Helicopter', icona:'🚁'},
                                {nome: 'Ferris Wheel', icona:'🎡'},
                                {nome: 'Moai Statue', icona:'🗿'}
];
